package com.jihelife.search.mapper;

import com.jihelife.search.dto.BaseTagModel;
import com.jihelife.search.dto.BaseTagModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseTagModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbggenerated Wed Oct 14 17:56:25 CST 2015
     */
    int countByExample(BaseTagModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbggenerated Wed Oct 14 17:56:25 CST 2015
     */
    int deleteByExample(BaseTagModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbggenerated Wed Oct 14 17:56:25 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbggenerated Wed Oct 14 17:56:25 CST 2015
     */
    int insert(BaseTagModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbggenerated Wed Oct 14 17:56:25 CST 2015
     */
    int insertSelective(BaseTagModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbggenerated Wed Oct 14 17:56:25 CST 2015
     */
    List<BaseTagModel> selectByExample(BaseTagModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbggenerated Wed Oct 14 17:56:25 CST 2015
     */
    BaseTagModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbggenerated Wed Oct 14 17:56:25 CST 2015
     */
    int updateByExampleSelective(@Param("record") BaseTagModel record, @Param("example") BaseTagModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbggenerated Wed Oct 14 17:56:25 CST 2015
     */
    int updateByExample(@Param("record") BaseTagModel record, @Param("example") BaseTagModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbggenerated Wed Oct 14 17:56:25 CST 2015
     */
    int updateByPrimaryKeySelective(BaseTagModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbggenerated Wed Oct 14 17:56:25 CST 2015
     */
    int updateByPrimaryKey(BaseTagModel record);
}